/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Skript47 (https://sketchfab.com/Skript47)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/computer-monitor-169-low-poly-game-ready-336de680dd9a4d84943d05d9c7dde1b0
Title: Computer Monitor 16:9 (Low Poly, Game Ready)
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
  };
  materials: {
    Monitor_01_A: THREE.MeshStandardMaterial;
    Monitor_01_B: THREE.MeshStandardMaterial;
  };
};

export function ComputerModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/computerModel/scene.gltf"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Monitor_01_A}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Monitor_01_B}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/computerModel/scene.gltf");
